import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sticker pro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <h1 className='text-3xl front-bold'>Sticker pro app</h1>
      </Head>
    </div>
  )
}
